%the following code simulate the operations of an green ammonia synthesis process using a wind farm and hydrogen storage, 
%the wind speed timeseries and relative power of the wind turbine must been imported
%open windspeed.xlsx and select the first column, import it as column vector and assign the name WS1
%open windspeed.xlsx and select the third column, import it as column vector and assign the name P_out
%% Wind Speed Nominal Interval Definition

wind_speed_nominal = 0:0.5:25; % From 3 to 25 m/s in 0.5 m/s step

% Example of real-time wind speed data (Insert real values every half hour)
% The variable WS1 is the the wind velocity array oin half hour steps
% (2 values for each hour)
T = readtable('wind speed.xlsx','Range','A:A');
First_column = T{:,1};
WS1=First_column;%
WS_h=(WS1(1:2:end)+WS1(2:2:end))/2;%calculation of average hourly value
% Mapping wind speeds to the closest nominal value
WS_mapped = round(WS_h * 2) / 2; % Rounding to the nearest 0.5 m/s

% Ensuring values stay within the defined range if velocity of wid higher
% than cut off set to 0
if WS_mapped > max(wind_speed_nominal)
    WS_mapped=0;

end
%% Time Series Setup 
year_selected = 2020;
start_time = datetime(year_selected, 1, 1, 0, 0, 0);
end_time = datetime(year_selected, 12, 31, 23, 0, 0); % Ensure it matches hourly resolution
timeseries1 = start_time:hours(1):end_time; % 1-hour time steps

%% Power Generation Calculationv
Y= readtable('wind speed.xlsx','Range','F2:F52');
Power_column = Y{:,1};
P_out=Power_column ;%vector power of the wind turbine in fuction of the wind speed
P_generated = (interp1(wind_speed_nominal, P_out, WS_mapped, 'linear', 0)); % Wind turbine power output kW


P_netta=P_generated;
%% INITIALISE 

optimal_turbines=24; %arbitrary

% Power generation from the wind farm
P_farm = P_netta * optimal_turbines; %Total wind farm net power (kW)
E_generated = P_farm / 1e3; % MWh
E_tot = sum(E_generated);%total energy generated by the wind farm
%E_tot_cf = sum((P_generated .* optimal_turbines) / 1e3);
cf=E_tot/(8760*optimal_turbines*4);%capacity factor of the plant (4 MW turbine)
fprintf('the capacity factor of the plant is: %.2f \n', cf);
%% Hydrogen production requirement (converted to constant power load)
m_H2required = (6481.3 * 1000 / 8760); % Required hydrogen flow (kg/h)
kWh_per_kg_H2 = 33.3; % PEM conversion factor (kWh/kg)
P_PEM_kW =41285; % Sizing PEM system by peak power (kW)
% Parameters
P_PEM_extra = max(P_farm)-P_PEM_kW; % [kW] fized power of the second PEM station
%% Battery model with degradatiuon (dinamically scaled)
% Parametri batteria
battery_capacity_kWh_single = 235000;% single battery capacity
P_batt_max_single = 3000;  % max power of charge/discharge of a battery [kW]
eta_charge = 0.95;%yeld of charge 
eta_discharge = 0.95;%yeld of discharge

%Calculation of the net power for a single battery
P_batt_eff_single = P_batt_max_single * eta_discharge;

% minumum number of batteries necessary to power the PEM 
n_batteries = ceil(P_PEM_kW / P_batt_eff_single);
fprintf('🔋 Minimum number of batteries required: %d\n', n_batteries);

% scaled paramiters for the battery Park
battery_capacity_kWh = battery_capacity_kWh_single * n_batteries;
P_batt_max = P_batt_max_single * n_batteries;

% Initialization
SOC = zeros(8760, 1);                  % state of charge [kWh]
SOC(1) = 0.75 * battery_capacity_kWh;  % initial SOC  (75%)
total_cycles = zeros(8760,1);          % cumulative cycles
SoH_battery = zeros(8760,1);           % state of health
SoH_battery(1) = 100;                  
P_disp = P_farm - P_PEM_kW;            % energetic surplus

% degradation's curve(empiric function)
SoH_fun = @(cyc) 100 - 5.613e-32*cyc.^9 + 3.121e-27*cyc.^8 - 6.353e-23*cyc.^7 ...
      + 6.630e-19*cyc.^6 - 3.987e-15*cyc.^5 + 1.435e-11*cyc.^4 ...
      - 3.070e-8*cyc.^3 + 3.746e-5*cyc.^2 - 0.0277*cyc;

end_life = false;
battery_output_energy = zeros(8760,1); % energy erogated from the batteries(kWh)

for t = 2:8760
    SoH_now = SoH_fun(total_cycles(t-1));
    SoH_battery(t) = SoH_now;
    capacity_available = battery_capacity_kWh * SoH_now / 100;

    if P_disp(t) >= 0
        charge_power = min(P_disp(t), P_batt_max);
        SOC(t) = SOC(t-1) + charge_power * eta_charge;
    else
        discharge_power = min(abs(P_disp(t)), P_batt_max);
        SOC(t) = SOC(t-1) - discharge_power * eta_discharge;
        battery_output_energy(t) = discharge_power; % Energia fornita (prima di efficienza)
    end

    SOC(t) = min(max(SOC(t), 0), capacity_available);

    % Calculation of the equivalent cycles 
    delta_SOC = abs(SOC(t) - SOC(t-1));
    cycle_rate = delta_SOC / capacity_available;
    total_cycles(t) = total_cycles(t-1) + cycle_rate / 2;

    if ~end_life && SoH_now < 70
        fprintf('⚠️ Battery at the end of life after %.1f cicli (anno: %.2f)\n', total_cycles(t), t/8760);
        end_life = true;
    end
end
E_battery_total_kWh = sum(battery_output_energy);%KWh
E_battery_lifetime=E_battery_total_kWh*20;%KWh
fprintf('🔋 Energia totale fornita dalla batteria durante l\''anno: %.2f kWh\n', E_battery_total_kWh);
LCOE_BATT= 0.292;% EUR/kWh
BATTERY_COST=(E_battery_lifetime*LCOE_BATT)/(10^3);%kEUR 
costo_batteria=(BATTERY_COST/3524879.41)*1000;%EUR/KWH




storage_size_batt = max(SOC);
figure(2);
subplot(3,1,1);
plot(timeseries1, SoH_battery, 'r', 'LineWidth', 1.5);
ylabel('SoH [%]');
title('Battery state of health (SoH) in time');
grid on;

subplot(3,1,2);
plot(timeseries1, total_cycles, 'b', 'LineWidth', 1.5);
ylabel('equivalent cycles');
title('Equivalent Number of Cycles in time ');
grid on;

subplot(3,1,3);
plot(timeseries1, SOC, 'g', 'LineWidth', 1.5);
xlabel('Tempo'); ylabel('SOC [kWh]');
title('State of charge (SOC) with degradation');
grid on;

%% Results
reserve_tot=sum(SOC);
fprintf('Optimal Number of Turbines: %d turbines\n', optimal_turbines);
fprintf('Minimum Required Battery Storage Capacity: %.2f kWh\n', storage_size_batt);
%% Hydrogen Production Breakdown (with extra PEM plant fixed + reserve control)

% Parameters
H2_reserve_max =200000; % [kg] maximum capacity of the reserve

% Initialisations 
H2_total = zeros(8760,1);
H2_from_wind = zeros(8760,1);
H2_from_batt = zeros(8760,1);
H2_reserve = zeros(8760,1);

H2_extra_total = 0;
H2_from_reserve_used = 0;
count_deficit_hours = 0;
count_reserve_use = 0;

for t = 1:8760
    % 1️⃣ H₂ from wind farm
    power_from_wind = min(P_farm(t), P_PEM_kW);
    
    
    % Efficiency curve application based on utilization rate
    Ur=(power_from_wind./P_PEM_kW)*100;
     L_s = 0.022; % 2.2%minimum threshold
     soglia_15 = 0.15; % 15% threshold
      Fy = 2030;
      eta = zeros(size(Ur));

      idx1 = Ur >= L_s & Ur < soglia_15;
      idx2 = Ur >= soglia_15;
      idx3=Ur<=L_s;


      eta(idx1) = ((0.00005*Ur(idx1).^5 - 0.0061*Ur(idx1).^4 + 0.2372*Ur(idx1).^3 - 4.2014*Ur(idx1).^2 + 36.675*Ur(idx1) - 62.87) * (1 + 0.0025)^(Fy - 2020)) ;
      eta(idx2) = ((-0.149*Ur(idx2) + 74.977) * (1 + 0.0025)^(Fy - 2020)) ;
      eta(idx3)=0;
      eta_dec=eta/100;
      H2_from_wind(t) = power_from_wind.*eta_dec /kWh_per_kg_H2;


    % 2️⃣ Deficit → battery turns on to supply
    power_deficit = P_PEM_kW - power_from_wind;
    battery_energy_available = min(SOC(t), P_batt_max); % [kWh]
    battery_contribution = 0;

    if power_deficit > 0 && battery_energy_available > 0
        battery_contribution = min(power_deficit, battery_energy_available * eta_discharge);
         Ur1=(battery_contribution./P_PEM_extra)*100;

      eta1 = zeros(size(Ur));

      idx4 = Ur1 >= L_s & Ur < soglia_15;
      idx6= Ur1 >= soglia_15;
      idx7=Ur<=L_s;

      eta1(idx4) = ((0.00005*Ur1(idx4).^5 - 0.0061*Ur1(idx4).^4 + 0.2372*Ur1(idx4).^3 - 4.2014*Ur1(idx4).^2 + 36.675*Ur1(idx4) - 62.87) * (1 + 0.0025)^(Fy - 2020)) ;
      eta1(idx6) = ((-0.149*Ur1(idx6) + 74.977) * (1 + 0.0025)^(Fy - 2020)) ;
      eta1(idx7)=0;
      eta1_dec=eta1/100;
    Pem_cons=55.8;
        H2_from_batt(t) =(battery_contribution) /Pem_cons; %(battery_contribution.*eta1_dec) /kWh_per_kg_H2;
    end

    % 3️⃣ total hydrogen produced without taking or putting in/from storage
    H2_total(t) = H2_from_wind(t) + H2_from_batt(t);
    H2_reserve_prev = H2_reserve(max(t-1,1));

    % 4️⃣ extra production for storage (PEM extra fixed)
    battery_full = SOC(t) >= (battery_capacity_kWh * SoH_battery(t)/100 * 0.99);
    surplus_power = P_farm(t) - P_PEM_kW;

    if battery_full && H2_total(t) >= m_H2required && surplus_power >= P_PEM_extra && H2_reserve_prev < H2_reserve_max
        Ur2=(surplus_power/P_PEM_extra)*100;

      eta2 = zeros(size(Ur));

      idx8= Ur2 >= L_s & Ur < soglia_15;
      idx9= Ur2 >= soglia_15;
      idx10=Ur<=L_s;

      eta2(idx8) = ((0.00005*Ur2(idx8).^5 - 0.0061*Ur2(idx8).^4 + 0.2372*Ur2(idx8).^3 - 4.2014*Ur2(idx8).^2 + 36.675*Ur2(idx8) - 62.87) * (1 + 0.0025)^(Fy - 2020)) ;
      eta2(idx9) = ((-0.149*Ur2(idx9) + 74.977) * (1 + 0.0025)^(Fy - 2020)) ;      
      eta2(idx10)=0;
      eta2_dec=eta2/100;
        extra_H2 =(surplus_power*eta2_dec) /kWh_per_kg_H2;
        spazio_riserva = H2_reserve_max - H2_reserve_prev;
 
        % always respect the maximum limit of the reserve
        extra_H2 = min(extra_H2, spazio_riserva);
        H2_reserve(t) = H2_reserve_prev + extra_H2;
        H2_extra_total = H2_extra_total + extra_H2;
    else
        H2_reserve(t) = H2_reserve_prev;
    end

    % 5️⃣ if deficit of H₂  → use the storaged one (reserve)
    if H2_total(t) < m_H2required
        count_deficit_hours = count_deficit_hours + 1;
        H2_needed = m_H2required - H2_total(t);
        H2_from_reserve = min(H2_needed, H2_reserve_prev);

        H2_total(t) = H2_total(t) + H2_from_reserve;
        H2_reserve(t) = H2_reserve_prev - H2_from_reserve;
        H2_from_reserve_used = H2_from_reserve_used + H2_from_reserve;

        if H2_from_reserve > 0
            count_reserve_use = count_reserve_use + 1;
           %fprintf("✅ Riserva usata in ora %d: %.2f kg\n", t, H2_from_reserve);
        end
    end
end

% final Debug info 
fprintf('\n⏳ Ore in deficit H₂: %d\n', count_deficit_hours);
fprintf('✅ Ore in cui è stata usata la riserva: %d\n', count_reserve_use);
fprintf('📤 Totale H₂ prelevato dalla riserva: %.2f kg\n', H2_from_reserve_used);
fprintf('📥 Totale H₂ accumulato nella riserva: %.2f kg\n', H2_extra_total);
fprintf('📦 Massima riserva H₂ raggiunta: %.2f kg\n', max(H2_reserve));
%%%FIXED COSTS 
%% ECONOMIC 
h_hub = 91.5; % high of the hub meters
R = 117/2; % Radius m
P_nom = 4000; % Nominal power kW
c_found = (303.24 * h_hub * (R^(2))*pi * 0.4037) / 1000;
c_transp = ((1.581E-5 * P_nom^2 - 0.0375 * P_nom + 54.7) * P_nom) / 1000;
c_instal = (1.965 * (h_hub^2 * R)^1.1736) / 1000;
c_civil = ((2.17E-6 * P_nom^2 - 0.0145 * P_nom + 69.54) * P_nom) / 1000;
c_eng = ((9.94E-4 * P_nom + 20.31) * P_nom) / 1000;
BOS=c_found+c_transp+c_instal+c_civil+c_eng;
TCC=4200000;
c_el_interf = ((3.49E-6*P_nom^2-0.0221*P_nom + 109.7)*P_nom)/1000; 
c_el_install = 0.65 * c_el_interf * optimal_turbines;
c_el=c_el_install;
CAPEX_turb=optimal_turbines*(BOS+TCC)+c_el;
eta_elec=0.95;
O_and_M=0.0007*E_tot;
decomissioning_cost=0.0107*P_nom*optimal_turbines;
land_fill_cost = 0.00108*E_tot;
OPEX = ((land_fill_cost+(1 / eta_elec)*(decomissioning_cost + O_and_M))/E_tot)*1000; 
%%HYDROGEN SYSTEM COSTS
Power_PEM=P_PEM_kW+P_PEM_extra;%KW
specific_cost_PEM=800;%eur/KW average value from papers
cost_PEM1=(specific_cost_PEM*Power_PEM)*1.1;%eur additional 10% for additional costs
specific_cost_PEM2032=113;%eur/KW assuming 60000h (8Y) of PEM life
specific_cost_PEM2040=68;%%eur/KW assuming 60000h (8Y) of PEM life
cost_PEM2=specific_cost_PEM2032*Power_PEM;%investment cost made for replace stack in 2032
cost_PEM3=specific_cost_PEM2040*Power_PEM;%investment cost made for replace stack in 2040
cost_PEM=cost_PEM1+cost_PEM2+cost_PEM3;% eur total cost for the hydrogen generation system
%HYDROGEN UNDERGROUND STORAGE COSTS
op_cost=0.32*0.92;%eur/kg
maint_cost=0.05*0.92;%eur/kg
d=0.1;%discount rate 
t=40;%well lifetime years
LCOS=1.5*0.92;%eur/kg levelised cost of electricity 
cushion_perc=0.5;% 50% of the reserve is filled bya cushion gas to ensure the proper working pressure 
reserve=165000+165000*cushion_perc;%kg H2
cf=0.8;%utilisation factor
level_TCC=LCOS*reserve+op_cost+maint_cost;%levelised cost of the riserve 
Hydrogen_stroage_cost=((cf*level_TCC*((1+d)^t-1))/(d*(1+d)^t))/1000;%cost of the investment Keur;
%% Compressor Cost (Oxygen)
n = 1.4;
p1H2 = 30e5;
p2O2 = 150e5;
C0_O2 = 2.327;
R_O2 = 259.81;
T_amb = 298.15;
eta_poly=0.8;
m_O2comprex = max(H2_total) * 8;
m_O2_dot = m_O2comprex / 3600;
P1_O2comp = ((m_O2_dot * R_O2 * T_amb * n / (eta_poly * (n - 1))) * ((p2O2 / p1H2)^((n - 1)/n) - 1)) / 1000;
P2_O2comp = P1_O2comp / 0.85;
P3_O2comp = P2_O2comp / 0.93;
P_O2comp = P3_O2comp / 0.97;
betaO2 = 5;
Comprex_cost_O2 = C0_O2 * (m_O2comprex * log(betaO2))^0.65;
%OTHERS FIXED COSTS 
Reactor_cost=231.2027;%Keur
Comprex_system_cost=1.1693e+03-897.6240+Comprex_cost_O2;%Keur
Cost_PEM_scaled=cost_PEM/1000;%Keur
N2_plant_cost=3.3596e+03;%Keur
other_cost=4.0936e+03;%Keur
wind_farm=CAPEX_turb/1000; %Keur
ammonia_loop= Reactor_cost+other_cost; %Keur
data = [ Comprex_system_cost, Cost_PEM_scaled,Reactor_cost,N2_plant_cost,BATTERY_COST, ammonia_loop,wind_farm,Hydrogen_stroage_cost];
percentuali = data / sum(data) * 100;
figure(4);
pie(data);
legend('Compression System Cost', 'Hydrogen System','Reactor Cost', 'Nitrogen','battery system','ammonia loop','wind farm','Hydrogen storage cost', 'Location', 'southeastoutside');
title(' Costs Distribution');

%% EVALUATION OF VARIABLE COSTS ARE MAINLY RELATED TO ELECTRICITY 
%OPEX
% Fixed Charge Rate formula
r=0.08;%dicount rate 
FCR = (r * (1 + r)^25) / ((1 + r)^25 - 1);
LCOE_wf=((FCR*CAPEX_turb)/E_tot)+OPEX;%eur/MWh
el_cost_pem=(LCOE_wf/1000)*(mean(eta/kWh_per_kg_H2))*(sum(H2_total)*8760);% eur/y cost of electricity for the production of hydrogen
I0=(ammonia_loop+ Comprex_system_cost+ Cost_PEM_scaled+ N2_plant_cost+wind_farm+Hydrogen_stroage_cost+BATTERY_COST)/10^3;
fixedOM=0.03*I0+OPEX;%fixed o&m costs from literature eur/y
E_c_tot=1.535227481997236e+07-(404.6583*8760)+(sum(P_O2comp*8769));%kWh
EL_comprex=(E_c_tot)*(10^-3)*LCOE_wf;%eur
totalvariable=el_cost_pem+fixedOM+EL_comprex;

%% CAPEX OF THE INVESTMENT 
NPV0=-I0*10^6;  % Start with the initial investment (negative)
%%
% FIND THE CAPEX WITH A INTEREST OF 8% AND A PAY BACK PERIOD OF 10 YEARS
oxygen_price = 150;
oxygen_production = m_O2comprex * 8760 / 1000;
REVENUE_oxygenY = oxygen_production * oxygen_price;

k=0.08;%interest rate fixed 8%
n_payback=10;%payback of investement
tlife=1:20;
t1=1:10;
t2=11:20;
alphafactor=(1-(1+k)^(-10))/k;
CAPEX=((-NPV0)/alphafactor);%total yearly capex  of the investment
CC=CAPEX;
OC=el_cost_pem+fixedOM+EL_comprex;
RO=REVENUE_oxygenY;
m_NH3=36500 ; %ton/y size methanol sinthesis process
LCONH3=(sum((CC+OC-RO)./(1+k).^t1)+sum((OC-RO)./(1+k).^t2))/(sum(m_NH3./((1+k).^tlife)));
%% Plot Results for Optimal Turbines
figure(3)
plot(timeseries1, H2_total, 'g', 'LineWidth', 1.5);
xlabel('Time');
ylabel('kg/h');
title('Hydrogen Production Over Time');
grid on
hold on;
yline(m_H2required, 'r', 'Required Hydrogen');
hold on 
%plot(timeseries1, SOC,'b')
hold off;
if any(H2_total < 737.85)
    fprintf('The hydrogen production is not sufficient\n');
    
else
    fprintf('The hydrogen production is sufficient\n');
end
figure(99)
plot(timeseries1,H2_reserve);
xlabel('Time');
ylabel('Hydrogen level kg'); 
title('Hydrogen storage Over Time');


